### PR TITLE
remove Serial set/get functions from dynamixel_io

### PR DESCRIPTION
**Pull request by anuragmakineni**
#48

### CODE REVIEW

**Comment by yoneken** [comment]
This PR helps me!

**Comment by jonbinney** [comment]
+1 this is needed for dynamixel driver to work on Ubuntu 16.04. Pyserial no longer has the `Serial.setSerial()` function.

**Comment by jonbinney** [comment]
Thanks @arebgun! I just updated master and can confirm that it works on 16.04.

**Comment by Opfour** [comment]
Linux 3.16.0-0.bpo.4-686-pae #1 SMP Debian 3.16.7-ckt25-2~bpo70+1 (2016-04-12) i686 GNU/Linux

Still getting the "Failed to communicate with radio: 'Serial' object has no attribute 'setTimeout' " error on this build

**Comment by jonbinney** [comment]
@Opfour what is `
Linux 3.16.0-0.bpo.4-686-pae #1 SMP Debian 3.16.7-ckt25-2~bpo70+1 (2016-04-12) i686 GNU/Linux`?

I just did a searc and can't find the word "radio" anywhere in this repo... what command did you run? Was there any other output?
