### ISSUE TITLE
'Serial' object has no attribute 'setTimeout'

### ISSUE THREAD

**Issue by anuragmakineni** [arebgun/dynamixel_motor#48]
After upgrading my PySerial version to V3.0 (current version), dynamixel_driver/dynamixel_io.py failed on the call to Serial.setTimeout(). Throwing the following error:

`'Serial' object has no attribute 'setTimeout'`

From this issue, https://github.com/pyserial/pyserial/issues/66 and https://github.com/pyserial/pyserial/commit/779b1a29594b9f6c69e73e02ab1e95b8dbb3e8b7 it looks like the set/get functions were deprecated in V2.x and completely removed in V3.0. I've submitted a pull request #49  to correct this issue.

**Comment by jonbinney** [comment]
@anuragmakineni I believe this was fixed by https://github.com/arebgun/dynamixel_motor/pull/49#event-729831692 - can this be closed?

**Comment by anuragmakineni** [comment]
Yep. Thanks for merging my PR @arebgun.
